kind: pipeline
type: docker
name: CI

platform:
  arch: arm64

clone:
  depth: 100

trigger:
  branch:
    - main
  event:
    - push
    - pull_request
    - tag

steps:
  - name: install
    image: oven/bun:1.3.3
    commands:
      - bun install --ignore-scripts

  - name: i18n-audit
    image: oven/bun:1.3.3
    commands:
      - (cd apps/web && bun run locale-check)
      - (cd apps/web && bun run locale-unused)
    depends_on:
      - install

  - name: typecheck
    image: oven/bun:1.3.3
    commands:
      - (cd apps/web && bun tsc --noEmit)
      - (cd apps/backend && bun tsc --noEmit)
      - (cd packages/backend-base && bun tsc --noEmit)
      - (cd packages/database && bun tsc --noEmit)
      - (cd packages/emails && bun tsc --noEmit)
      - (cd packages/api && bun tsc --noEmit)
      - (cd packages/ui && bun tsc --noEmit)
    depends_on:
      - install

  - name: lint
    image: oven/bun:1.3.3
    commands:
      - bun biome ci .

    depends_on:
      - typecheck

  - name: build-database
    image: oven/bun:1.3.3
    commands:
      - (cd packages/database && bun run build)
    depends_on:
      - install
      - typecheck
      - lint

  - name: build-backend
    image: oven/bun:1.3.3
    commands:
      - (cd apps/backend && bun run build)
    depends_on:
      - build-database

  - name: build-web
    image: oven/bun:1.3.3
    commands:
      - (cd apps/web && bun run build)
    depends_on:
      - build-backend
