services:
  database:
    image: postgres:latest
    container_name: origin-starter-database
    environment:
      POSTGRES_DB: origin-starter
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
  stripe:
    image: stripe/stripe-cli:latest
    container_name: stripe
    command: listen --forward-to http://host.docker.internal:3333/stripe/webhook
    env_file:
      - ./apps/backend/.env
    depends_on:
      - database
