services:
  database:
    image: postgres:latest
    container_name: origin-starter-database
    environment:
      POSTGRES_DB: origin-starter
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
  stripe:
    image: stripe/stripe-cli:latest
    container_name: stripe
    command: listen --forward-to http://host.docker.internal:3000/api/stripe/webhook
    environment:
      STRIPE_WEBHOOK_SECRET: whsec_4be7d23c91c2b79093393067292d3a278356eab836d6da476c399d909139b4dc
    depends_on:
      - database
