sonar.projectKey=project-key-ignite-starter
sonar.organization=org-key-evo

# Sources
sonar.sources=\
  apps/web/src,\
  apps/backend/src,\
  packages/backend-base/src,\
  packages/database/src,\
  packages/emails/src,\
  packages/ui/src

# Exclusions
sonar.exclusions=\
  **/node_modules/**,\
  **/generated/**,\
  **/.next/**,\
  **/dist/**,\
  **/build/**,\
  **/coverage/**,\
  **/*.gen.ts,\
  **/*.test.ts,\
  **/*.test.tsx,\
  **/*.spec.ts,\
  **/*.spec.tsx,\
  **/.storybook/**,\
  **/storybook-static/**, \
  **/*.stories.ts,\
  **/*.stories.tsx,\
  **/stories/**

# Temporary: ignore coverage metric
sonar.coverage.exclusions=**/*

# Coverage paths
sonar.javascript.lcov.reportPaths=\
  apps/web/coverage/lcov.info,\
  packages/backend-base/coverage/lcov.info,\
  packages/ui/coverage/lcov.info
