sonar.projectKey=ignite-starter_ignite-starter
sonar.organization=ignite-starter

# Sources
sonar.sources=\
  apps/web/src,\
  apps/backend/src,\
  packages/backend-base/src,\
  packages/database/src,\
  packages/emails/src,\
  packages/ui/src

# Exclusions
sonar.exclusions=\
  **/node_modules/**,\
  **/generated/**,\
  **/.next/**,\
  **/dist/**,\
  **/build/**,\
  **/coverage/**,\
  **/*.gen.ts,\
  **/*.test.ts,\
  **/*.test.tsx,\
  **/*.spec.ts,\
  **/*.spec.tsx,\
  **/.storybook/**,\
  **/storybook-static/**, \
  **/*.stories.ts,\
  **/*.stories.tsx,\
  **/stories/**,\
  # TODO: (eng) - Remove these files from the exclusion when they are ready to be analyzed
  **/components/ui/**,\
  **/lib/shadcn/**,\
  **/feature/dashboard/components/**,\
  **/providers/**,\
  **/app/layout.tsx,\
  **/sonner.tsx

# Coverage paths
sonar.javascript.lcov.reportPaths=\
  apps/web/coverage/lcov.info,\
  packages/backend-base/coverage/lcov.info,\
  packages/ui/coverage/lcov.info
